spring:
  datasource:
    url: jdbc:h2:mem:finance
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true # resource/*.sql ??? ???? ???? ??
    database-platform: H2
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true

  redis:
    host: localhost
    port: 16379

#  jwt:
#    secret: ZGF5b25lLXNwcmluZy1ib290LXByb2plY3QtdHV0b3JpYWwtand0LXNlY3JldC1rZXkK
#
#scheduler:
#  scrap:
#    yahoo: 0 0 0 * * *